version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    env_file:
      - backend/.env
  frontend:
    build: ./frontend
    ports:
      - 8080:80
    depends_on:
      - backend
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: