version: '3'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - mailhog
    environment:
      JWT_SECRET: "^FoxWSn7Ts^69ERD&6yN%@YxJ"
      EMAIL_HOST: "mailhog"
      EMAIL_PORT: "1025"
      EMAIL_SECURE: "false"
      EMAIL_USER: "test"
      EMAIL_PASS: "test"
      MONGO_URI: "mongodb://mongodb:27017/loadfm"
      FRONTEND_URL: "http://localhost:8080"
    volumes:
      - ./backend:/app
    command: npx nodemon app.mjs
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"
      FAST_REFRESH: false
      WDS_SOCKET_PORT: 8080
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
